const data = [
  { id: 1, country: "United States"},
  { id: 2, country: "Germany"},
  { id: 3, country: "Italy"},
  { id: 4, country: "France"},
  { id: 5, country: "Japan"},
  { id: 6, country: "United Kingdom"},
  { id: 7, country: "Korea"},
  { id: 8, country: "Netherlands"},
  { id: 9, country: "Austria"},
  { id: 10, country: "Switzerland"},
  { id: 11, country: "Brazil"},
  { id: 12, country: "Spain"},
  { id: 13, country: "China"},
  { id: 14, country: "Canada"},
  { id: 15, country: "Australia"},
  { id: 16, country: "Finland"},
  { id: 17, country: "Estonia"},
  { id: 18, country: "Taiwan"},
  { id: 19, country: "Poland"},
  { id: 20, country: "Mexico"},
  { id: 21, country: "United Arab Emirates"},
  { id: 22, country: "Sweden"},
  { id: 23, country: "Hong Kong"},
  { id: 24, country: "Slovakia"},
  { id: 25, country: "Denmark"},
  { id: 26, country: "Turkey"},
  { id: 27, country: "Slovenia"},
  { id: 28, country: "Hungary"},
  { id: 29, country: "Cyprus"},
  { id: 30, country: "Costa Rica"},
  { id: 31, country: "New Zealand"},
  { id: 32, country: " Thailand"},
  { id: 33, country: "Philippines"},
  { id: 34, country: "Uruguay"},
  { id: 35, country: "Belgium"},
  { id: 36, country: "Indonesia"},
  { id: 37, country: "India"},
  { id: 38, country: "Guyana"},
  { id: 39, country: "Israel"},
  { id: 40, country: "Bahrain"},
  { id: 41, country: "Ireland"},
  { id: 42, country: "Panama"},
  { id: 43, country: "Bulgaria"},
  { id: 44, country: "Singapore"},
  { id: 45, country: "Georgia"},
  { id: 46, country: "Norway"},
  { id: 47, country: "Lithuania" },
  { id: 48, country: "Bermuda" },
  { id: 49, country: "Colombia"},
  { id: 50, country: "Czechia"},
  { id: 51, country: "Latvia"},
  { id: 52, country: "Ukraine" },
  { id: 53, country: "Moldova"},
  { id: 54, country: "El Salvador" },
  { id: 55, country: "South Africa" },
  { id: 56, country: "Dominican Republic"},
  { id: 57, country: "Albania" },
  { id: 58, country: "Uzbekistan"},
  { id: 59, country: " Kazakhstan" },
  { id: 60, country: "Honduras" },
  { id: 61, country: "Portugal" },
  { id: 62, country: "Malaysia" },
  { id: 63, country: "Chile "},
];

var geochart=webix.ui({
  type: "head",
  container: "geoChart_container",
  rows: [
    {
      view: "geochart",
      id: "map",
      data: data,
      height:450,
      key: "AIzaSyAi0oVNVO-e603aUY8SILdD4v9bVBkmiTg",
      tooltip: "",
      chart: {
        legend: "none",
        backgroundColor: "#EEECF8",
        datalessRegionColor: "#D8B1EA",
        defaultColor: "#AB0592",
      },
    },
  ],
});

geochart.adjust();

// webix.ui({
//   type: "head",
//   container: "geoChart_container",
//   rows: [
//     {
//       view: "geochart",
//       id: "map",
//       data: data,
//       width: 760,
//       height: 450,
//       key: "AIzaSyAi0oVNVO-e603aUY8SILdD4v9bVBkmiTg",
//       tooltip: "",
//       chart: {
//         legend: "none",
//         backgroundColor: "#EEECF8",
//         datalessRegionColor: "#D8B1EA",
//         defaultColor: "#AB0592",
//       },
//     },
//   ],
// });

// $$("geochart").adjust();

